# Generated by Django 5.2.14 on 2026-06-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_articles', models.IntegerField(default=0)),
                ('published_articles', models.IntegerField(default=0)),
                ('pending_articles', models.IntegerField(default=0)),
                ('source_statistics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
