# Generated by Django 5.2.14 on 2026-06-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='openai', max_length=40)),
                ('model', models.CharField(default='gpt-4.1-mini', max_length=120)),
                ('temperature', models.FloatField(default=0.3)),
                ('max_tokens', models.IntegerField(default=1200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
